export const plans = [
  {
    id: "0",
    title: "Basic",
    priceMonthly: 149,
    priceYearly: 1789,
    caption: "Best for Start-ups",
    features: [
      "Keyword Research (AI-optimized for your niche)",
      "Meta Title & Description Generation",
      "Basic Content Optimization (Top 5 pages)",
      "Google My Business Setup",
      "Monthly Performance Report",
    ],
    icon: "/plans/circle.svg",
    logo: "/plans/plan-1.png",
  },
  {
    id: "1",
    title: "Premium",
    priceMonthly: 399,
    priceYearly: 4788,
    caption: "Most popular plan",
    features: [
      "Everything in Basic, plus:",
      "Competitor SEO Analysis (AI-driven)",
      "Internal Linking Optimization",
      "Blog Content Suggestions + AI Drafts (4/mo)",
      "Schema Markup & Rich Snippets",
      "Mobile & Core Web Vitals Optimization",
      "AI-based Image Alt Text & File Naming",
      "Bi-Weekly SEO Reports with Insights",
    ],
    icon: "/plans/hexagon.svg",
    logo: "/plans/plan-2.png",
  },
  {
    id: "2",
    title: "Diamond",
    priceMonthly: 899,
    priceYearly: 10788,
    caption: "Exclusively for businesses",
    features: [
      "Everything in Premium, plus:",
      "Full Website SEO Audit (AI + Human Expert Reviewed)",
      "Programmatic SEO Strategy & Execution",
      "AI-Generated SEO Landing Pages (up to 20/mo)",
      "Dynamic Content Suggestions based on SERP trends",
      "AI Chatbot for SEO Queries (included for your team)",
      "Conversion Rate Optimization Recommendations",
      "Weekly Strategy Calls & Custom Roadmap",
    ],
    icon: "/plans/hexagon.svg",
    logo: "/plans/plan-3.png",
  },
];
